--CONEXION TEMA12ESTUDIO

/*Ejercicio propuesto:
Escribe un disparador que inserte en la tabla auditaremple(col1 (VARCHAR2(200)) cualquier cambio
que supere el 5% del salario del empleado indicando la fecha y hora, el empleado, y el salario
anterior y posterior.*/

CREATE TABLE AUDITAREMPLE (
INFORMACION VARCHAR2(200)); --TABLA PA MOSTRAR MENSAJE

CREATE OR REPLACE TRIGGER audit_salario --CREAS TRIGGER
    AFTER UPDATE OF SALARIO ON EMPLE -- CUANDO SE ACTUALICE LA TABLA 
    FOR EACH ROW -- POR CADA LINEA
WHEN (NEW.SALARIO > OLD.SALARIO*1.05) -- CUANDO EL SALARIO NUEVO SEA 5% MAYOR QUE EL ANTIGUO
BEGIN
        INSERT INTO AUDITAREMPLE --INSERTAR EN LA TABLA MENSAJE
        VALUES (TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI') || ' ' || :NEW.EMP_NO || ' ANTIGUO SALARIO: ' || :OLD.SALARIO ||
        ' NUEVO SALARIO: ' || :NEW.SALARIO);
END;
/

SELECT * FROM EMPLE WHERE DEPT_NO = 10;

UPDATE EMPLE 
SET SALARIO = 400000
WHERE DEPT_NO = 10;

SELECT * FROM AUDITAREMPLE;


--CONEXION_TEMA12PARTE3ESTUDIO TABLA POBLACION


